name: Build
on: [ push, pull_request ]

jobs:
  build-ubuntu-shared:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build shared library
      run: |
        cmake -S . -B build -DBUILD_SHARED_LIBS=ON
        cd build
        make
  build-ubuntu-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build static library
      run: |
        cmake -S . -B build -DBUILD_SHARED_LIBS=OFF
        cd build
        make
      