name: Test
on: [ push, pull_request ]

jobs:
  test-shared:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests with shared linking
      run: |
        cmake -S . -B build -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
        cd build
        sudo make install
        sudo ldconfig
        echo "Library built and installed"
        cd ../tests
        cmake -S . -B build -G "Unix Makefiles"
        cd build
        make tests
        ./tests
  test-static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests with static linking
      run: |
        cmake -S . -B build -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF
        cd build
        sudo make install
        echo "Library built and installed"
        cd ../tests
        cmake -S . -B build -G "Unix Makefiles"
        cd build
        make tests
        ./tests
      
