name: Test
on: [ push, pull_request ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: |
        mkdir build
        cmake -S . -B build -DDO_TESTS=ON
        cd build
        make install
        make unit-test
        ./unit-test
      