name: Test
on: [ push, pull_request ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: |
        cmake -S . -B build -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON
        cd build
        sudo make install
        sudo ldconfig
        echo "Library built and installed"
        cd ../tests
        cmake -S . -B build
        cd build
        make unit-test
        ./unit-test
      